// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Thu May 30 21:27:51 2024

dc dc_inst
(
	.a0(a0_sig) ,	// input  a0_sig
	.a1(a1_sig) ,	// input  a1_sig
	.a2(a2_sig) ,	// input  a2_sig
	.a3(a3_sig) ,	// input  a3_sig
	.b0(b0_sig) ,	// output  b0_sig
	.b1(b1_sig) ,	// output  b1_sig
	.b2(b2_sig) ,	// output  b2_sig
	.b3(b3_sig) ,	// output  b3_sig
	.b4(b4_sig) ,	// output  b4_sig
	.b5(b5_sig) ,	// output  b5_sig
	.b6(b6_sig) ,	// output  b6_sig
	.b7(b7_sig) ,	// output  b7_sig
	.b8(b8_sig) ,	// output  b8_sig
	.b9(b9_sig) ,	// output  b9_sig
	.b10(b10_sig) ,	// output  b10_sig
	.b11(b11_sig) ,	// output  b11_sig
	.b12(b12_sig) ,	// output  b12_sig
	.b13(b13_sig) ,	// output  b13_sig
	.b14(b14_sig) ,	// output  b14_sig
	.b15(b15_sig) 	// output  b15_sig
);

